"""Local TTS playback for SparkyBot fight commentary.

Supports two providers:
  - edge:        Microsoft edge-tts neural voices (free, no API key, online)
  - elevenlabs:  ElevenLabs API (high quality, API key required)

Public API
----------
generate_tts_bytes(text, config) -> Optional[bytes]
    Standalone function. Generates audio as raw MP3 bytes synchronously.
    No Qt dependency. Called from the fight-processing worker thread.
    Used for both Discord attachment and local playback hand-off.

TTSClient (QObject)
    Owns QMediaPlayer on the Qt main thread. Queue-based so back-to-back
    fights never overlap. Accepts either text (generates audio) or
    pre-generated bytes (skips generation, used when Discord attachment
    already generated the audio).
"""

import logging
import os
import queue
import tempfile
import threading
import time
from typing import Optional, Union

import requests

from PyQt6.QtCore import QObject, QUrl, pyqtSignal
from PyQt6.QtMultimedia import QAudioOutput, QMediaPlayer

logger = logging.getLogger(__name__)

MAX_RETRIES = 2


# ------------------------------------------------------------------------------
# Standalone audio generation — no Qt, safe to call from any thread
# ------------------------------------------------------------------------------

def generate_tts_bytes(text: str, config) -> Optional[bytes]:
    """Generate TTS audio and return raw MP3 bytes synchronously.

    Called from the fight-processing worker thread (not the Qt main thread).
    Returns None on any failure so callers can degrade gracefully.
    """
    if not text or not text.strip():
        return None

    provider = getattr(config, "tts_provider", "edge").lower()

    if provider == "elevenlabs":
        return _generate_elevenlabs(text, config)
    return _generate_edge(text, config)


def _generate_edge(text: str, config) -> Optional[bytes]:
    """Generate audio via Microsoft edge-tts (free, no API key)."""
    try:
        import asyncio
        import edge_tts
    except ImportError:
        logger.error("edge-tts not installed. Run: pip install edge-tts")
        return None

    voice = getattr(config, "tts_edge_voice", "en-GB-RyanNeural")

    async def _stream() -> bytes:
        communicate = edge_tts.Communicate(text, voice)
        chunks = []
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                chunks.append(chunk["data"])
        return b"".join(chunks)

    loop = asyncio.new_event_loop()
    try:
        logger.info(f"Generating edge-tts audio (voice={voice})")
        return loop.run_until_complete(_stream())
    except Exception as e:
        logger.error(f"edge-tts generation failed: {e}")
        return None
    finally:
        loop.close()


def _generate_elevenlabs(text: str, config) -> Optional[bytes]:
    """Generate audio via ElevenLabs REST API."""
    api_key = getattr(config, "tts_elevenlabs_api_key", "").strip()
    if not api_key:
        logger.error("ElevenLabs API key not configured")
        return None

    voice_id = getattr(config, "tts_elevenlabs_voice_id", "").strip() or "JBFqnCBsd6RMkjVDRZzb"
    stability = float(getattr(config, "tts_elevenlabs_stability", 0.35))
    similarity_boost = float(getattr(config, "tts_elevenlabs_similarity_boost", 0.75))
    style = float(getattr(config, "tts_elevenlabs_style", 0.15))
    use_speaker_boost = bool(getattr(config, "tts_elevenlabs_speaker_boost", True))
    speed = float(getattr(config, "tts_elevenlabs_speed", 1.0))
    speed = max(0.7, min(1.2, speed))

    logger.info(
        f"Generating ElevenLabs audio "
        f"(voice={voice_id}, "
        f"stability={stability:.2f}, similarity={similarity_boost:.2f}, "
        f"style={style:.2f}, speed={speed:.2f}, speaker_boost={use_speaker_boost})"
    )

    for attempt in range(MAX_RETRIES + 1):
        try:
            response = requests.post(
                f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}",
                headers={
                    "xi-api-key": api_key,
                    "Content-Type": "application/json",
                },
                json={
                    "text": text,
                    "model_id": "eleven_monolingual_v1",
                    "voice_settings": {
                        "stability": stability,
                        "similarity_boost": similarity_boost,
                        "style": style,
                        "use_speaker_boost": use_speaker_boost,
                        "speed": speed,
                    }
                },
                timeout=30,
            )
            if response.status_code in (500, 503) and attempt < MAX_RETRIES:
                logger.warning(f"ElevenLabs returned {response.status_code}, retrying in 2s...")
                time.sleep(2)
                continue
            response.raise_for_status()
            return response.content

        except requests.Timeout:
            if attempt < MAX_RETRIES:
                logger.warning(f"ElevenLabs timed out, retrying in 2s...")
                time.sleep(2)
                continue
            logger.error("ElevenLabs request timed out after all retries")
            return None
        except Exception as e:
            logger.error(f"ElevenLabs generation failed: {e}")
            return None

    return None


# ------------------------------------------------------------------------------
# TTSClient — Qt main thread, owns QMediaPlayer
# ------------------------------------------------------------------------------

class TTSClient(QObject):
    """Plays TTS audio locally via QMediaPlayer.

    Must be instantiated on the Qt main thread. Accepts either:
      - speak(text)        — generates audio then plays
      - speak_from_bytes(bytes) — plays pre-generated audio directly
    """

    _play_requested = pyqtSignal(str)  # path to temp MP3

    def __init__(self, config, parent=None):
        super().__init__(parent)
        self.config = config

        # Queue items are: str (text), bytes (pre-generated), or None (stop)
        self._queue: queue.Queue = queue.Queue()
        self._stop_event = threading.Event()
        self._playback_done = threading.Event()
        self._playback_done.set()

        self._current_temp: Optional[str] = None

        self._audio_output = QAudioOutput()
        self._player = QMediaPlayer()
        self._player.setAudioOutput(self._audio_output)
        self._player.mediaStatusChanged.connect(self._on_media_status_changed)
        self._set_volume(self.config.tts_volume)

        self._play_requested.connect(self._play_file)

        self._worker = threading.Thread(
            target=self._worker_loop, name="TTSWorker", daemon=True
        )
        self._worker.start()
        logger.info(
            f"TTSClient started (provider={self.config.tts_provider}, "
            f"volume={self.config.tts_volume})"
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def speak(self, text: str) -> None:
        """Queue text for generation + playback. Non-blocking."""
        if not self.config.tts_enabled:
            return
        if not text or not text.strip():
            return
        self._queue.put(text.strip())

    def speak_from_bytes(self, audio_bytes: bytes) -> None:
        """Queue pre-generated audio bytes for playback. Non-blocking.
        Use when Discord attachment already generated the audio to avoid
        generating twice."""
        if not self.config.tts_enabled:
            return
        if not audio_bytes:
            return
        self._queue.put(audio_bytes)

    def stop(self) -> None:
        """Signal worker to exit. Call on application shutdown."""
        self._stop_event.set()
        self._queue.put(None)

    def update_volume(self, volume: int) -> None:
        """Apply new volume (0-100) immediately."""
        self._set_volume(volume)

    # ------------------------------------------------------------------
    # Worker thread
    # ------------------------------------------------------------------

    def _worker_loop(self) -> None:
        while not self._stop_event.is_set():
            try:
                item = self._queue.get(timeout=1.0)
            except queue.Empty:
                continue

            if item is None:
                break

            self._playback_done.wait()
            self._playback_done.clear()

            if isinstance(item, bytes):
                # Pre-generated audio
                path = _write_temp(item)
            else:
                # Text — generate now
                path = self._generate_to_file(item)

            if path:
                self._play_requested.emit(path)
            else:
                self._playback_done.set()

        logger.debug("TTSWorker exiting")

    def _generate_to_file(self, text: str) -> Optional[str]:
        """Generate audio and write to temp file. Returns path or None."""
        audio_bytes = generate_tts_bytes(text, self.config)
        if not audio_bytes:
            return None
        return _write_temp(audio_bytes)

    # ------------------------------------------------------------------
    # Playback (Qt main thread via signal)
    # ------------------------------------------------------------------

    def _play_file(self, path: str) -> None:
        self._cleanup_temp()
        self._current_temp = path
        self._set_volume(self.config.tts_volume)
        self._player.setSource(QUrl.fromLocalFile(os.path.abspath(path)))
        self._player.play()
        logger.debug(f"TTS playback started: {path}")

    def _on_media_status_changed(self, status: QMediaPlayer.MediaStatus) -> None:
        terminal = (
            QMediaPlayer.MediaStatus.EndOfMedia,
            QMediaPlayer.MediaStatus.InvalidMedia,
            QMediaPlayer.MediaStatus.NoMedia,
        )
        if status in terminal:
            if status == QMediaPlayer.MediaStatus.InvalidMedia:
                logger.warning(f"TTS playback failed — invalid media: {self._current_temp}")
            self._playback_done.set()
            logger.debug(f"TTS playback finished (status={status.name})")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _set_volume(self, volume: int) -> None:
        clamped = max(0, min(100, volume)) / 100.0
        self._audio_output.setVolume(clamped)

    def _cleanup_temp(self) -> None:
        if self._current_temp and os.path.exists(self._current_temp):
            try:
                os.remove(self._current_temp)
            except OSError:
                pass
        self._current_temp = None


# ------------------------------------------------------------------
# Module-level helpers (no Qt dependency)
# ------------------------------------------------------------------

def _write_temp(data: bytes, suffix: str = ".mp3") -> Optional[str]:
    try:
        fd, path = tempfile.mkstemp(suffix=suffix, prefix="sparkybot_tts_")
        with os.fdopen(fd, "wb") as f:
            f.write(data)
        return path
    except OSError as e:
        logger.error(f"Failed to write TTS temp file: {e}")
        return None
